// Base item type definitions (NWN base item IDs)
// This is a subset of common base items

export const BASE_ITEMS: Record<number, string> = {
  0: "Shortsword",
  1: "Longsword",
  2: "Battleaxe",
  3: "Bastardsword",
  4: "Light Flail",
  5: "Warhammer",
  6: "Longbow",
  7: "Light Mace",
  8: "Halberd",
  9: "Shortbow",
  10: "Two-Bladed Sword",
  11: "Greatsword",
  12: "Small Shield",
  13: "Torch",
  14: "Armor",
  15: "Helmet",
  16: "Greataxe",
  17: "Amulet",
  18: "Arrow",
  19: "Belt",
  20: "Dagger",
  21: "Miscellaneous Small",
  22: "Bolt",
  23: "Boots",
  24: "Bullet",
  25: "Club",
  26: "Miscellaneous Medium",
  27: "Dart",
  28: "Dire Mace",
  29: "Doubleaxe",
  30: "Miscellaneous Large",
  31: "Heavy Flail",
  32: "Gloves",
  33: "Light Hammer",
  34: "Handaxe",
  35: "Healers Kit",
  36: "Kama",
  37: "Katana",
  38: "Kukri",
  39: "Miscellaneous Tall",
  40: "Light Crossbow",
  41: "Heavy Crossbow",
  42: "Light Lance",
  43: "Morningstar",
  44: "Quarterstaff",
  45: "Rapier",
  46: "Ring",
  47: "Scimitar",
  48: "Scythe",
  49: "Large Shield",
  50: "Tower Shield",
  51: "Short Spear",
  52: "Shuriken",
  53: "Sickle",
  54: "Sling",
  55: "Thief Tools",
  56: "Throwing Axe",
  57: "Trap Kit",
  58: "Key",
  59: "Large Box",
  60: "Miscellaneous Wide",
  61: "Creature Slash Weapon",
  62: "Creature Pierce/Bludgeon Weapon",
  63: "Creature Bludgeon Weapon",
  64: "Creature Slash/Pierce Weapon",
  65: "Creature Pierce Weapon",
  66: "Gold",
  67: "Gem",
  68: "Bracer",
  69: "Cloak",
  70: "Spellbook",
  71: "Blank Potion",
  72: "Blank Scroll",
  73: "Blank Wand",
  74: "Enchanted Potion",
  75: "Enchanted Scroll",
  76: "Enchanted Wand",
  77: "Book",
  78: "Trident",
  79: "Whip",
  80: "Sai",
  81: "Falchion",
  82: "Flute",
  83: "Nunchaku",
  84: "Drum",
  85: "Mandolin",
  86: "Warmace",
  87: "Heavy Pick",
  88: "Light Pick",
  89: "Elven Lightblade",
  90: "Elven Thinblade",
  91: "Orc Double Axe",
  92: "Dwarven Waraxe",
  93: "Mercurial Longsword",
  94: "Mercurial Greatsword",
  95: "Kawashigi",
  96: "Heavy Trident",
  97: "Throwing Star",
  98: "Throwing Spear",
  99: "Empty Bag",
  100: "Small Bag",
  101: "Medium Bag",
  102: "Large Bag",
  103: "Huge Bag",
  108: "Lightning Nunchaku",
  109: "Fire Nunchaku",
  110: "Ice Nunchaku",
  111: "Holy Bow",
  112: "Unholy Bow",
  113: "Repeating Crossbow",
};

export function getBaseItemName(id: number): string {
  return BASE_ITEMS[id] || `Unknown (${id})`;
}
